version: 0.2	
        
phases:
  install:
    on-failure: ABORT | CONTINUE
    runtime-versions:
      java : correttor8
    commands:
      - echo install  
  pre_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo pre_build
  build:
    on-failure: ABORT | CONTINUE
    commands:
      - mvn clean package
      - echo $CODEBUILD_SRC_DIR
      - echo build
    
  post_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo post_build    

artifacts:
  files:
    -'**/*'
    - target/02-todo-rest-api-h2-0.0.1-SNAPSHOT.jar
   discard-paths:true